# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
cache: packages

r:
- oldrel
- release
- devel

env:
  - KERAS_BACKEND="tensorflow"

r_binary_packages: 
  - rstan

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - pip2.7 install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - R -e 'tensorflow::install_tensorflow()'

before_install:
  - sudo apt-get -y install libnlopt-dev

after_success:
  - Rscript -e 'covr::codecov()'
