# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: true

r:
- release
- devel

env:
  global:
  - KERAS_BACKEND="tensorflow"
  - MAKEFLAGS="-j 2"

r_binary_packages: 
 - rstan
 - rstanarm
 - igraph
 - RCurl
 - dplyr
 - git2r
 - shiny
 - glue
 - magrittr
 - stringi
 - colorspace
 - assertthat
 - utf8
 - stringr
 - RColorBrewer
 - dichromat
 - munsell
 - labeling
 - R6
 - viridisLite
 - cli
 - crayon
 - pillar
 - rlang
 - digest
 - gtable
 - plyr
 - reshape2
 - scales
 - tibble
 - lazyeval
 - ggplot2
 - StanHeaders
 - inline
 - gridExtra
 - Rcpp
 - RcppEigen
 - BH

cache:
  packages: false
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip


before_script:
  - python -m pip install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - python -m pip install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - R -e 'tensorflow::install_tensorflow()'

before_install:
  - sudo apt-get -y install libnlopt-dev 
  - sudo apt-get update
  - sudo apt-get -y install python3
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14 = clang++ -arch x86_64 -ftemplate-depth-256" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14FLAGS = -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-unknown-pragmas" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CC = clang" >> ~/.R/Makevars; fi

after_success:
  - Rscript -e 'covr::codecov()'
  - travis_wait 59 Rscript -e 'covr::coveralls(line_exclusions="src/init.cpp")'
